### ISSUE TITLE
[bug] A rule whose last character is a backslash does not detect logs correctly

### ISSUE THREAD

**Issue by fukusuket** [Yamato-Security/hayabusa#1025]
**Describe the bug**
A rule like the one below with a `backslash as the last character` does not detect logs correctly 🤔
```
e.g.
detection:
    selection:
        EventID: 1040
        Data|startswith: C:\Windows\
    condition: selection
```

**Step to Reproduce**

1. Create following rule and save the file as `test.yml`
  ```
  title: TEST
  id: 66366687-b855-4e12-a353-71cc52351cab
  status: test
  author: TEST
  date: 2023/05/02
  logsource:
      product: windows
      service: application
  detection:
      selection:
          EventID: 1040
          Data|startswith: C:\Windows\
      condition: selection
  falsepositives: unknown
  level: low
  ```
2. Execute following command.
  ```.\hayabusa-2.4.0-win-x64.exe csv-timeline -f C:\tmp\hayabusa-sample-evtx\DeepBlueCLI\many-events-application.evtx -r C:\tmp\test.yml  ```

**Expected behavior**
Logs containing `C:\Windows\` are detected. (`44` detections)

**Actual behavior**
Nothing detected.

**Environment**

- OS:  `Windows 10 Version 22H2`
- hayabusa version ~`v.2.4.0`
  - I was able to reproduce this issue with `v1.8.1` as well. It seems to be an issue since the initial release.

**Additional context**
The following rules also does not detect logs with hayabusa-sample-evtx, so it's a problem that happens regardless of fields or logs. It also happened with `contains`, not just `startswith`.
```
title: TEST2
id: d0edff07-38f9-4875-a407-2ad5d0c13f31
status: test
author: TEST2
date: 2023/05/02
logsource:
    product: windows
    category: process_creation
detection:
    selection:
        EventID: 1
        Channel: Microsoft-Windows-Sysmon/Operational
        ParentImage|contains: C:\Windows\
    condition: selection
falsepositives: unknown
level: low
```

e.g.(Example of rules affected by this issue in the Sigma repo)
- [SigmaHQ/sigma: win_msi_install_from_susp_locations.yml](https://github.com/SigmaHQ/sigma/blob/ef95e5278d9130de2a00c948156f05b959acfd02/rules/windows/builtin/application/msiinstaller/win_msi_install_from_susp_locations.yml)
  - but rules converted by `hayabusa-rules/converter.py` are not affected as they convert `startswith/contains` into `wildcard pattern`

I will investigate the cause some more 🤔

**Comment by YamatoSecurity** [comment]
@fukusuket What if you do `Data|startswith: 'C:\Windows\'` ?

**Comment by YamatoSecurity** [comment]
@fukusuket Nevermind, i tried
```
detection:
    selection:
        ParentImage|startswith: 'C:\Windows'
    condition: selection
```
and
```
detection:
    selection:
        ParentImage|startswith: 'C:\Windows\'
    condition: selection
```
and indeed the rule does not match if it ends with a `\`!
This is a big bug..
