### ISSUE TITLE
[bug]  Panic occurs when a non-existent `Data` field is specified in `details` of a rule

### ISSUE THREAD

**Issue by fukusuket** [Yamato-Security/hayabusa#1215]
**Describe the bug**
Normally, an existing `Data` field index is specified in `details`, but in rare cases (e.g. JSON input), there is no `Data` field, which causes a panic.

**Step to Reproduce**
1. Save the following rule with the file name test.yml.
```yml
author: TEST
date: 2023/11/12
modified: 2023/11/12

title: 'PwShClassic'
details: 'Data: %Data[2]%'
description: 'TEST'

id: ac2ae63b-83e6-4d06-aeaf-07409bda92c9
level: informational
status: test
logsource:
    product: windows
    service: powershell
detection:
    selection:
        Channel: 'Windows PowerShell'
    condition: selection
falsepositives:
tags:
references:
ruletype: Hayabusa
```
2. Download [apt29_evals_day1_manual.zip](https://github.com/OTRF/Security-Datasets/blob/master/datasets/compound/apt29/day1/apt29_evals_day1_manual.zip) and unzip.
3. `./hayabusa-2.10.0-mac-arm csv-timeline -f ../apt29_evals_day1_manual_2020-05-01225525.json -J -r test.yml -w -q`

**Actual behavior**
panic occurs as follows:
```
% ./hayabusa-2.10.0-mac-arm csv-timeline -f ../apt29_evals_day1_manual_2020-05-01225525.json -J -r test.yml -w -q
Start time: 2023/11/12 21:57

Total event log files: 1
Total file size: 385.3 MB


Loading detection rules. Please wait.


Test rules: 1 (100.00%)

Hayabusa rules: 1
Total enabled detection rules: 1

Output profile: standard

Scanning in progress. Please wait.

[00:00:00] 0 / 1 ⠁ [                                        ] 0%

"../apt29_evals_day1_manual_2020-05-01225525.json"                                                                                             thread 'hayabusa-thread' panicked at src/detections/message.rs:324:18:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/detections/detection.rs:176:41:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(1009), ...)
```

**Expected behavior**
panic does not occur.

**Environment**
- OS: macOS sonoma 14.0
- hayabusa version 2.10.0 (I haven't confirmed this, but it seems like this is probably an issue that existed in previous versions)
