### ISSUE TITLE
not used `!` chracter in field of rule

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa#1283]
**Describe the bug**

 no detected `!` chracter in field of rule.

**Step to Reproduce**

1. prepared following rule  (ex: test.yml)

```
...
title: 'Suspicious LDAP Request for Kerberoasting'
description: 'Suspicious LDAP Request for Kerberoasting'

id: a9fcb928-9ed6-4ea0-8c52-cd62ec54403b
level: medium
status: test
logsource:
    product: windows
    service: security
detection:
    selection_basic:
        Channel: Directory Service
        EventID: 1644
    selection_SuspiciousFilter:
      # Data: '( & (objectClass=user) (servicePrincipalName=*) ( ! (cn=krbtgt) ) ( ! (sAMAccountType=805306369) ) )'
      # Data: '*! (sAMAccountType=805306369) ) )'
        Data: '* (sAMAccountType=805306369) ) )'
    condition: selection_basic and selection_SuspiciousFilter
falsepositives:
   - unknown
ruletype: Hayabusa
```

3. `hayabusa.exe csv-timeline -f ./kerberos.evtx -r ./test/yml`
4. not detected EID 1644 records

**Expected behavior**

Records with EID 1644 matching the criteria must be detected.

**Environment (please complete the following information):**

- hayabusa version [e.g. v1.0.0] 2.13.0
