### ISSUE TITLE
Sigma correlation rule count does not show up in 'Events with hits'

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1373]
@fukusuket Sorry I noticed this bug after merging the previous PR..

I am using this rule:
```
title: Value Count TEST
id: 0e95725d-7320-415d-80f7-004da920fc11
level: high
correlation:
  type: value_count
  rules:
    - 8afa97ce-a217-4f7c-aced-3e320a57756d
    - e87bd730-df45-4ae9-85de-6c75369c5d29
  group-by:
    - Computer
  timespan: 5m
  condition:
    gte: 2
    field: SubStatus
---
title: Logon Failure (User Does Not Exist)
description: Prints failed logons

id: 8afa97ce-a217-4f7c-aced-3e320a57756d
level: medium
logsource:
  product: windows
  service: security
detection:
  selection_basic:
    Channel: Security
    EventID: 4625
  selection_user_not_exist:
    SubStatus: "0xc0000064" #Username does not exist error
  condition: selection_basic and selection_user_not_exist
---
title: Logon Failure (Wrong Password)
description: Prints logon information.

id: e87bd730-df45-4ae9-85de-6c75369c5d29
level: low
logsource:
  product: windows
  service: security
detection:
  selection_basic:
    Channel: Security
    EventID: 4625
  selection_wrong_password:
    SubStatus: "0xc000006a" #Wrong password
  condition: selection_basic and selection_wrong_password
```

and this command: `./target/release/hayabusa csv-timeline -d ../hayabusa-sample-evtx -w -r ~/Desktop/test.yml`

It gives me this summary:
```
Results Summary:

Events with hits / Total events: 0 / 26,341 (Data reduction: 26,341 events (100.00%))

Total | Unique detections: 2 | 1
Total | Unique critical detections: 0 (0.00%) | 0 (0.00%)
Total | Unique high detections: 2 (100.00%) | 1 (0.00%)
Total | Unique medium detections: 0 (0.00%) | 0 (0.00%)
Total | Unique low detections: 0 (0.00%) | 0 (0.00%)
Total | Unique informational detections: 0 (0.00%) | 0 (100.00%)

Dates with most total detections:
critical: n/a, high: 2021-05-20 (1), medium: n/a, low: n/a, informational: n/a

Top 5 computers with most unique detections:
critical: n/a
high: n/a
medium: n/a
low: n/a
informational: n/a

╭──────────────────────────────────────────────────╮
│ Top critical alerts:        Top high alerts:     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ n/a                         Value Count TEST (2) │
│ n/a                         n/a                  │
│ n/a                         n/a                  │
│ n/a                         n/a                  │
│ n/a                         n/a                  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top medium alerts:          Top low alerts:      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ n/a                         n/a                  │
│ n/a                         n/a                  │
│ n/a                         n/a                  │
│ n/a                         n/a                  │
│ n/a                         n/a                  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top informational alerts:                        │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ n/a                         n/a                  │
│ n/a                         n/a                  │
│ n/a                         n/a                  │
│ n/a                         n/a                  │
│ n/a                         n/a                  │
╰───────────────────────────╌──────────────────────╯
```

Problems:
1. `Top 5 computers with most unique detections` shows only `n/a` but should include the correlation rule results
2. `Events with hits / Total events: 0 / 26,341 (Data reduction: 26,341 events (100.00%))` should say `Events with hits / Total events: 2 / 26,341 (Data reduction: 26,339 events (99.99%))`
