### ISSUE TITLE
[bug] `ComplexData` fields are not extracted correctly

### ISSUE THREAD

**Issue by fukusuket** [Yamato-Security/hayabusa#1520]
**Describe the bug**
`ComplexData` fields are not extracted correctly. 

**Step to Reproduce**
```yml
author: TEST
date: 2024/11/30
title: "TEST"
id: 9fa273cc-bcb2-4789-85e3-14ca253ac7f4
level: informational
status: test
logsource:
  product: windows
  service: system
detection:
  selection:
    Channel: System
    EventID: 26
  condition: selection
```
`./hayabusa-2.19.0-mac-aarch64 json-timeline -d ../hayabusa-sample-evtx -r test.yml -w`

**Actual behavior**
2.19.0
```json
{
    "Timestamp": "2016-09-20 22:07:36.609 +09:00",
    "RuleTitle": "TEST",
    "Level": "info",
    "Computer": "IE10Win7",
    "Channel": "Sys",
    "EventID": 26,
    "RecordID": 8286,
    "Details": {},
    "ExtraFieldInfo": {
        "ComplexData": "",
        "Group": 0,
        "IdleStateCount": 1,
        "Name": ["IdleState", "PerfState"],
        "Number": 0,
        "PerfStateCount": 0,
        "ThrottleStateCount": 8
    }
}
```

2.18.0
```json
{
    "Timestamp": "2016-09-20 22:07:36.609 +09:00",
    "RuleTitle": "TEST",
    "Level": "info",
    "Computer": "IE10Win7",
    "Channel": "Sys",
    "EventID": 26,
    "RecordID": 8286,
    "Details": {},
    "ExtraFieldInfo": {
        "ComplexData": 1,
        "Group": 0,
        "IdleStateCount": 1,
        "Name": "PerfState",
        "Number": 0,
        "PerfStateCount": 0,
        "ThrottleStateCount": 8
    }
}
```

**Expected behavior**
Perhaps the following outputs(Expected results will need to be discussed)
```json
{
    "Timestamp": "2016-09-20 22:07:36.609 +09:00",
    "RuleTitle": "TEST",
    "Level": "info",
    "Computer": "IE10Win7",
    "Channel": "Sys",
    "EventID": 26,
    "RecordID": 8286,
    "Details": {},
    "ExtraFieldInfo": {
        "Group": 0,
        "IdleStateCount": 1,
        "Number": 0,
        "PerfStateCount": 0,
        "ThrottleStateCount": 8
        "IdleState": 1,
        "PerfState": ""
    }
}
```

**Screenshots**

**Environment**

- OS: macOS Sequoia 15.1.1
- hayabusa version 2.19.0 2.18.0(I haven't checked, but I think it occurs in earlier versions as well)

**Additional context**
I think the difference between `2.19.0` and `2.18.0` is due to the merge of the following. (neither version is extracting correctly).
- https://github.com/Yamato-Security/hayabusa-evtx/pull/70
- https://github.com/omerbenamram/evtx/pull/245
