### ISSUE TITLE
[bug] Correlation rules are not referencing the rule ID of `another file`

### ISSUE THREAD

**Issue by fukusuket** [Yamato-Security/hayabusa#1523]
**Describe the bug**
Correlation rules are not referencing the rule ID of another file.

**Step to Reproduce**
```yml
title: Correlation TEST
id: 0e95725d-7320-415d-80f7-004da920fc11
level: informational
correlation:
  type: value_count
  rules:
    - 8afa97ce-a217-4f7c-aced-3e320a57756d
    - e87bd730-df45-4ae9-85de-6c75369c5d29
  group-by:
    - Computer
  timespan: 5m
  condition:
    gte: 2
    field: SubStatus
```
`./hayabusa-2.19.0-mac-aarch64 csv-timeline -d ../hayabusa-sample-evtx -w -r test.yml`

**Actual behavior**
```
Rule parsing errors: 1
...
[WARN] Failed to parse rule. (FilePath : test.yml) The referenced rule was not found: e87bd730-df45-4ae9-85de-6c75369c5d29
```

**Expected behavior**
No Rule parse error

**Environment**
- OS: macOS Sequoia 15.1.1
- hayabusa version: 2.16.0~ (Occurs from the initial release of the Correlation rule feature)

**Additional context**
The reasons for no rule parsing errors in Ver 2.6.0~2.7.1 are as follows
- https://github.com/Yamato-Security/hayabusa/issues/1444

If a reference rule is written within the same rule, this issue will not occur. For example, the following rule will not generate parse error.
```yml
title: Value Count TEST
id: 0e95725d-7320-415d-80f7-004da920fc11
level: informational
correlation:
  type: value_count
  rules:
    - rule-a
    - rule-b
  group-by:
    - Computer
  timespan: 5m
  condition:
    gte: 2
    field: SubStatus
---
title: Logon Failure (User Does Not Exist)
name: rule-a

logsource:
  product: windows
  service: security
detection:
  selection_basic:
    Channel: Security
    EventID: 4625
  selection_user_not_exist:
    SubStatus: "0xc0000064" #Username does not exist error
  condition: selection_basic and selection_user_not_exist
---
title: Logon Failure (Wrong Password)
name: rule-b

logsource:
  product: windows
  service: security
detection:
  selection_basic:
    Channel: Security
    EventID: 4625
  selection_wrong_password:
    SubStatus: "0xc000006a" #Wrong password
  condition: selection_basic and selection_wrong_password
```
