### ISSUE TITLE
[bug] `expand` rules get hits even when not configured

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1620]
@fukusuket 
If you run all of the rules with `-w` on the challenge data from our DFIR contest last week, we get the `User with Privileges Logon` alert. `b3d10465-f171-0ef7-d28e-8ef2f9409cf1`

This is the detection logic:
```
detection:
    security:
        Channel: Security
    selection:
        EventID:
            - 4672
            - 4964
    filter_main_local_system:
        SubjectUserSid: S-1-5-18
    filter_main_valid_account:
        SubjectUserName|expand: '%Admins_Workstations%' # Set valid internal naming pattern or a list a valid account
    condition: security and (selection and not 1 of filter_main_*)
```

Maybe this rule is being used because the `expand` modifier is being used as a filter?
It should not be loaded unless `Admins_Workstations.txt` is configured, correct?
