### ISSUE TITLE
deprecatedルールのスキップオプションの追加

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa#220]
deprecated(SIGMAの中でも廃棄されたルール)を無視するためのオプションの作成

## 背景
SIGMAのルールにはstatusがdeprecatedとなっているルールがあります。下記がその例です。
このようなルールは誤検知/過検知が多いので、読み込まないようにしたいです。
```````````````````````````````
title: Suspicious PowerShell Download
id: 65531a81-a694-4e31-ae04-f8ba5bc33759
status: deprecated
description: Detects suspicious PowerShell download command
tags:
    - attack.execution
    - attack.t1059.001
    - attack.t1086  #an old one
author: Florian Roth
date: 2017/03/05
modified: 2021/09/21
logsource:
    product: windows
    service: powershell
detection:
    webclient:
        - 'System.Net.WebClient'
    download:
        - '.DownloadFile('
        - '.DownloadString('
    condition: webclient and download
falsepositives:
    - PowerShell scripts that download content from the Internet
level: medium
```````````````````````````````

## 仕様
* hayabusaのコマンドライン引数に```--no-deprecated```が付与された場合に、statusがdeprecatedと記載されているルールは読み込まない。
* このオプションはsigmaルールを想定したオプションだが、特にhayabusaルールとsigmaルールを分けて考える必要はなく、statusがdeprecatedなら読み込まないような処理を加えてもらえればそれでOKです。
* 標準出力に出る```Ignored Rule Count```にここでスキップしたルールファイルの数を追加する。
