### ISSUE TITLE
正しくcount出来ていない

### ISSUE THREAD

**Issue by hach1yon** [Yamato-Security/hayabusa#278]
# やること
SIGMAルールのcountの意味を調べるために、sigmacを使用してSIGMAルールをsplunkクエリとsqliteクエリに変換し、[ここ](https://github.com/Yamato-Security/hayabusa/blob/main/doc/AboutRuleCreation-Japanese.md#aggregation-condition)の理解が正しいことを検証する。

# 検証結果のまとめ
[ここ](https://github.com/Yamato-Security/hayabusa/blob/main/doc/AboutRuleCreation-Japanese.md#aggregation-condition)の理解は正しいっぽい。

# 検証結果の詳細
## 実行するsigmacのコマンド
``````
python ./tools/sigmac -t splunk --config ./tools/config/generic/sysmon.yml --defer-abort ./rules/windows/builtin/win_susp_failed_logons_single_process.yml
```````

## テストに使ったSIGMAルール
下記のルールをベースにcount()の式をちょっとずつ変更して検証していきます。

`````
title: Multiple Users Failing to Authenticate from Single Process
id: fe563ab6-ded4-4916-b49f-a3a8445fe280
description: Detects failed logins with multiple accounts from a single process on the system.
status: experimental
author: Mauricio Velazco
date: 2021/06/01
modified: 2021/07/07
references:
    - https://docs.splunk.com/Documentation/ESSOC/3.22.0/stories/UseCase#Active_directory_password_spraying
    - https://www.trimarcsecurity.com/single-post/2018/05/06/trimarc-research-detecting-password-spraying-with-security-event-auditing
tags:
    - attack.t1110.003
    - attack.initial_access
    - attack.privilege_escalation
logsource:
    product: windows
    service: security
detection:
    selection1:
        EventID: 4625
    condition:
        - selection1 | count() > 10
falsepositives:
    - Terminal servers
    - Jump servers
    - Other multiuser systems like Citrix server farms
    - Workstations with frequently changing users
level: medium
`````

## テストするパターン
下記の4パターンをテストします。[ここ](https://github.com/Yamato-Security/hayabusa/blob/main/doc/AboutRuleCreation-Japanese.md#aggregation-condition)で説明するパターンと同じです。

![キャプチャ](https://user-images.githubusercontent.com/32596618/145542781-578b11b6-d8d8-43fb-8448-2f3201470ec0.PNG)

### テストするdetection
`````
detection:
    selection1:
        EventID: 4625
    condition:
        - selection1 | count() > 10
`````

### 出力されたクエリ
* splunk
`````
EventID="4625" | eventstats count as val | search val > 10
`````

* sqlite
`````
SELECT * FROM (SELECT *,count(*) AS agg FROM eventlog WHERE EventID = "4625") WHERE agg > 10
`````

### 検証結果
これは流石に間違えようがない。、[ここ](https://github.com/Yamato-Security/hayabusa/blob/main/doc/AboutRuleCreation-Japanese.md#aggregation-condition)の一番最初に説明しているパターンと同じ。

### テストするdetection
`````
detection:
    selection1:
        EventID: 4625
    condition:
        - selection1 | count(TargetUser) > 10
`````

### 出力されたクエリ
* splunk
`````
EventID="4625" | eventstats dc(TargetUser) as val | search val > 10
`````

* sqlite
`````
SELECT * FROM (SELECT *,count(TargetUser) AS agg FROM eventlog WHERE EventID = "4625") WHERE agg > 10
`````

### 検証結果
splunkのdcというコマンドの意味は[ここ](https://www.splunk.com/pdfs/solution-guides/splunk-quick-reference-guide-jp.pdf)に書いてある。splunkのdcというコマンド意味を考えると、[ここ](https://github.com/Yamato-Security/hayabusa/blob/main/doc/AboutRuleCreation-Japanese.md#aggregation-condition)の2番目のパターンと同じ意味のクエリになっていることが確認できた。

### テストするdetection
`````
detection:
    selection1:
        EventID: 4625
    condition:
        - selection1 | count() by process > 10
`````

### 出力されたクエリ
* splunk
`````
EventID="4625" | eventstats count as val by process| search val > 10
`````

* sqlite
`````
SELECT * FROM (SELECT *,count(*) AS agg FROM eventlog WHERE EventID = "4625" GROUP BY process) WHERE agg > 10
`````

### 検証結果
sqliteの方を見ると、`countのby`は`sqlのgroup by`にあたることが判明。ということは、[ここ](https://github.com/Yamato-Security/hayabusa/blob/main/doc/AboutRuleCreation-Japanese.md#aggregation-condition)の3番目のパターンと多分同じ意味と考えて良さそう。

### テストするdetection
`````
detection:
    selection1:
        EventID: 4625
    condition:
        - selection1 | count(TargetUser) by process > 10
`````

### 出力されたクエリ
* splunk
`````
EventID="4625" | eventstats dc(TargetUser) as val by process | search val > 10
`````

* sqlite
`````
SELECT * FROM (SELECT *,count(TargetUser) AS agg FROM eventlog WHERE EventID = "4625" GROUP BY process) WHERE agg > 10
`````

### 検証結果
これも、[ここ](https://github.com/Yamato-Security/hayabusa/blob/main/doc/AboutRuleCreation-Japanese.md#aggregation-condition)の4番目のパターンと多分同じ意味っぽい。
