### ISSUE TITLE
[bug] Rules that use `Data` field won't work

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#775]
**Describe the bug**
`Data|contains|`、`Data:`等を使うルールは正しく検知しません。Applicationログの15件のルールがそれを使っています。
例: `application/win_esent_ntdsutil_abuse.yml`
元々のルール:
```
detection:
    selection:
        Provider_Name: 'ESENT'
        EventID:
            - 216
            - 325
            - 326
            - 327
        Data|contains: 'ntds.dit'
    condition: selection
```
Hayabusaルールに変換されると`Data: '*ntds.dit*'`になります。

イベントログはこんな感じ:
<img width="1209" alt="Screen Shot 2022-10-22 at 18 21 34" src="https://user-images.githubusercontent.com/71482215/197335033-145c92b1-eb78-43c6-8007-e6ac765c0280.png">
複数の`Data`フィールドがあります。

hayabusa-rulesレポジトリの[Readme](https://github.com/Yamato-Security/hayabusa-rules/blob/main/README-Japanese.md#eventdata%E3%81%AE%E4%BE%8B%E5%A4%96%E7%9A%84%E3%81%AA%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3)に書いてありますが、複数のDataフィールドで検索したい場合は`Data:`ではなくて、`EventData:`というフィールドを使う必要があります。`rules/sigma/builtin/application/win_esent_ntdsutil_abuse.yml`のhayabusaルールで`Data: '*ntds.dit*'`を`EventData: '*ntds.dit*'`に変えたら正しく検知できました。

イベントキーアリアス(`rules/config/eventkey_alias.txt`)で直せるかなと試しましたが、駄目でした。
`Data,Event.EventData.Data`と`Data,Event.EventData`を試しましたが、駄目でした。

なので、Hayabusaの方で修正する必要があります。
Dataフィールドを検索しているのに、EventDataを指定する必要があるのは分かりにくいのと、Sigmaルールは`Data`を使っているので、`EventData`の利用をやめて、Sigmaルールに合わせたいです。

※現在、`EventData: hogehoge`を使うhayabusaルールは３件ありますが、1.8.0をリリースしたら、`Data:`に変更しようと思っています。

**Step to Reproduce**
`./hayabusa-1.8.0-dev -d ../hayabusa-sample-evtx -r rules/sigma/builtin/application/win_esent_ntdsutil_abuse_susp_location.yml`

**Expected behavior**
Ntdsutil Abuseのアラートが出るはずです。

- OS: mac
- hayabusa version: up to 1.7.2
