### ISSUE TITLE
Support `|cidr`

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#955]
Some rules are now using `|cidr`.
Example (builtin/security/win_security_successful_external_remote_rdp_login.yml)
```
title: External Remote RDP Logon from Public IP
id: 259a9cdf-c4dd-4fa2-b243-2269e5ab18a2
detection:
    selection:
        EventID: 4624
        LogonType: 10
    filter:
        SubjectUserName: '-'
        IpAddress|cidr:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
            - 224.0.0.0/4
            - 127.0.0.0/8
    condition: selection and not filter
```

I think we can use the `cidr-utils` crate to handle this. 
@fukusuket Are you interested in this issue?
